includes:
- configs/FRED/defaults.yaml

setup:
  # Lx: 12
  # Ty: 4
  Lx: 3   #lag length
  Ty: 1   #lag length
  dim_x : 56
  dim_y : 9
  freq_ratio: 3
  bidirectional_encoder: False
  model_type: 'MTMFSeq2One'
  
train:
  n_a: 128
  n_s: 256
  # n_a: 1024
  # n_s: 512
  n_align: 16
  fc_x: 256
  fc_y: 128
  # fc_x: 1024
  # fc_y: 512
  dropout_rate: 0.4
  l1reg: 0.0001
  l2reg: 0.0001
  learning_rate: 0.0002
  shuffle: True
